//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeShareAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ImageBase64 { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Details { get; set; }
        public bool Preview { get; set; }
        public int CategoryId { get; set; }
    }
}
