IF DB_ID('Angular') IS NULL
BEGIN
	CREATE DATABASE Angular
END

USE Angular

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Users')
BEGIN
	CREATE TABLE dbo.Users	
	( User_id INT PRIMARY KEY IDENTITY(1,1) Not Null ,
	  Username VARCHAR(50) ,
	  Password VARCHAR(MAX)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Users')
BEGIN
	CREATE TABLE dbo.Product
	( ProductId INT PRIMARY KEY IDENTITY(1,1) Not Null,
	  ProductName VARCHAR(100),
	  Deleted bit not null 
	);
END

